### ISSUE TITLE
A domain/ip filter option would be great

### ISSUE THREAD

**Issue by BenjaminSoelberg** [mandiant/flare-floss#304]
May I suggest to add a string filtering option to the CLI. A build-in domain/ip filter could be provided.

**Comment by Ana06** [comment]
You can do this combining floss with [grep](https://en.wikipedia.org/wiki/Grep). For example:

`floss my-file.exe | grep -E "([12]{0,1}[0-9]{1,2}\.){3}[12]{0,1}[0-9]{1,2}"`

which returns things like:
```
0.0.0.0
196.5.7.44
255.255.255.0
168.255.298.21
```

Those kind of regular expressions could be added in floss under a `suspicious` option which includes things like:

- urls
- IPs
- domains
- files
- registers

Even if the list is not perfect, it would save you some time as if the strings list is too long you most likely have to filter the output with grep (or in other way) for those cases.

I do not think though that adding an option only for domain/ip is a good idea, because if there was an option for every type of important string, the options list would get to long. I prefer to have just one option for everything. :thinking: 

@BenjaminSoelberg, @williballenthin what do you think? can I send a PR for the `suspicious` option?

**Comment by mr-tz** [comment]
We've discussed this a while ago in #163. Back then we decided to not invent another "interesting strings database". However, I like the straight-forward solution provided in #312. Thanks, Ana!
@williballenthin thoughts?

**Comment by williballenthin** [comment]
I agree that the implementation in #312 is an easy addition. 

It may be worth merging because it does add a concrete, useful feature to the tool.

My primary concern is about the maintenance required to maintain and update this "database". In practice, its probably not *hard*, though it duplicates work done elsewhere (TODO: where? I claim it does exist, but where can we actually look for prior art?).

**Comment by williballenthin** [comment]
Here's a potentially alternative implementation: use [StringSifter](https://github.com/fireeye/stringsifter) to decide what should be highlighted.

the benefit is that we can rely on work done elsewhere and leave it to them to be experts.

the con is that it won't be easy to tweak (e.g. if StringSifter may not think `kernel32.dll` is _interesting_, but if its decoded as a stack string, it probably still is for FLOSS).

maybe we don't use StringSifter for filtering, but just for ordering (by default). 

Though it may appear so, I promise I'm not trying to push only FireEye tech on FLOSS. Just seemed like a relevant project that would be easy to integrate (`import stringsifter`).

**Comment by Ana06** [comment]
@williballenthin 

> My primary concern is about the maintenance required to maintain and update this "database"

I think there is no much maintenance as long as we keep the solution simple. From my PR:

> I tried to keep the regular expressions simple (i.e. it returns strings similar to IPs that are not IPs such as 299.0.0.0) to avoid making the code difficult to read/modify

It is also not really a database (except by the windows libraries list, but this won't change that often and it is also not that important if you would get a few of them), but a set of "as generic as possible" regular expressions, which shouldn't need to be updated (expect by improvements, but not really to keep it working).

> Here's a potentially alternative implementation: use StringSifter to decide what should be highlighted 
>
> the benefit is that we can rely on work done elsewhere and leave it to them to be experts.

That is a good point. I also like this idea.

> the con is that it won't be easy to tweak (e.g. if StringSifter may not think kernel32.dll is interesting, but if its decoded as a stack string, it probably still is for FLOSS).

Now that you mention, I am thinking that we may not want to filter any of the stack strings (which I am doing in my PR). That would be solved in both cases (either using my PR or StringSifter) by not filtering in this case.

**Comment by mr-tz** [comment]
Closing stale issue, see above and #163 for context.
