### ISSUE TITLE
Show how many times a specific `decoding function` has been called

### ISSUE THREAD

**Issue by r0ny123** [mandiant/flare-floss#693]
Currently, floss can identify the `decoding functions` in a binary and prints them with `offset` and `score` while running usng `-v` flag. Now, it's maybe useful to know that how many times a functions has been called which may better indicate several decoding routine present in the binary under analysis.

**Comment by RahulSankhla312** [comment]
Hello , could you assign this issue to me .  I have kind of made some changes , could you check it ?
<img width="891" alt="image" src="https://github.com/mandiant/flare-floss/assets/97101245/fd7c2031-2fd0-47d2-80a5-678a590d0c9c">

**Comment by mr-tz** [comment]
You got it. Maybe @r0ny123 can specify a bit on what to display: number of xrefs to a function, number of emulated calls, etc. Curious to see what you display here.

**Comment by RahulSankhla312** [comment]
@r0ny123 could you please specify me what to do next ?

**Comment by RahulSankhla312** [comment]
@mr-tz @r0ny123 Could you please specify on what i need to do next now ?

**Comment by mr-tz** [comment]
Let's start on what you've done above. What were your thoughts and how did you go about them?

**Comment by RahulSankhla312** [comment]
When I thought about adding a feature to FLOSS to track how often each decoding function is called, I had a few key ideas in mind:

1. I wanted to give people using FLOSS more insight into which decoding functions the binary file uses the most. This information could help someone figure out which functions play a big role in hiding or changing data, making their analysis more focused and efficient.

2. Since FLOSS already finds and runs these decoding functions by simulating (or "emulating") the program, I thought about keeping track of each time a function is called. For this, I used a dictionary function which would do the job well.

3. My goal was to add this new tracking feature without altering too much of FLOSS's existing code. This way, we can improve FLOSS without risking the stable parts of the program that already work well.

I see these ideas as just the beginning of making FLOSS even better. By introducing this feature thoughtfully, I aimed to make FLOSS not just more powerful for advanced users, but also more helpful and accessible for everyone, aligning with the tool's main goals and offering real benefits to its users.


@mr-tz Please correct me if i missed something.

**Comment by mr-tz** [comment]
If you already have some code feel free to open a PR, maybe it's easier to discuss in there concretely on the implementation. I'm curious to see how your count differs from the call counts displayed in the progress bar line.

**Comment by RahulSankhla312** [comment]
https://github.com/mandiant/flare-floss/pull/958 - Please check this PR

**Comment by RahulSankhla312** [comment]
@mr-tz could you provide me with the changes required or is it ok ?

**Comment by RahulSankhla312** [comment]
@r0ny123 Ok , I'll work upon it .

**Comment by mr-tz** [comment]
@r0ny123, to clarify: do you mean how often a function is called as analyzed via static analysis (I.e. all the code cross-references to a function)?

**Comment by r0ny123** [comment]
Yes, cross references(I should have mentioned it).

**Comment by RahulSankhla312** [comment]
@r0ny123  could you please provide me with the command , to get this type of flare floss results .
<img width="632" alt="image" src="https://github.com/mandiant/flare-floss/assets/97101245/d91da7f0-4d24-49f0-b062-2623fcc2ae67">

**Comment by r0ny123** [comment]
Run floss with `-v` flag.

**Comment by RahulSankhla312** [comment]
@mr-tz @r0ny123 ?

**Comment by RahulSankhla312** [comment]
@mr-tz @r0ny123 could you tell me if the count values like this are correct ?

**Comment by RahulSankhla312** [comment]
https://github.com/mandiant/flare-floss/pull/968 please check this pr @mr-tz @r0ny123 
<img width="550" alt="call_count" src="https://github.com/mandiant/flare-floss/assets/97101245/5836e2eb-0e29-45aa-8207-23faf4b26498">
This is the new output as you suggested .

**Comment by mr-tz** [comment]
That looks great. @r0ny123, does that meet your expectations?
Maybe instead of calls we use xrefs to (depending on the implementation)?

**Comment by RahulSankhla312** [comment]
@r0ny123 Thankyou!!

**Comment by r0ny123** [comment]
Closing as already fixed with https://github.com/mandiant/flare-floss/pull/978.
